### ISSUE TITLE
not able to import the package

### ISSUE THREAD

**Issue by koustav051199** [Simon-Bertrand/Clusters-Features#2]
I successfully downloaded the package as mentioned in the documentation but whenever I am trying to import the package it is showing module not found error.

**Comment by Simon-Bertrand** [comment]
First of all, hello,

Secondly, you need to provide example for your issue. Examples : Environnement details, how you installed the library, "pip list" standard output and things that can help to resolve your issue.

As it is not concerning the core of the library but rather your Python environment and your PIP manager, i close this issue.

Thank you

**Comment by koustav051199** [comment]
Thanks for the reply.
Please find the attached images explaining my issue.
I have created an environment test2 and installed the package there using
the command "pip install Clusters-Features".
The installed package is also visible in "pip list" but I cannot import it.

Please help.
Thank you.
